ktor {
    deployment {
        port = 8081
        port = ${?PORT}
    }
    application {
        modules = [org.multipaz.verifier.ApplicationKt.module]
    }
}

verifier {
    # Public base URL of this server (no trailing slash)
    baseUrl = "http://localhost:8081"
    baseUrl = ${?BASE_URL}
}
